-- BrainTwist 当前成就初始化数据
-- 依赖 docs/成就系统接入说明.md 中的 achievement_definitions 表结构。

INSERT INTO achievement_definitions (
  achievement_key,
  game_key,
  game_mode,
  category,
  title,
  description,
  icon,
  reward_type,
  reward_amount,
  target_value,
  condition_key,
  sort_order,
  is_hidden,
  is_enabled
) VALUES
  (
    'tutorial',
    'reverse_brain',
    'classic',
    'growth',
    '初来乍到',
    '完成新手教程',
    'face-pink-wink',
    'coin',
    10,
    1,
    'tutorial_complete',
    10,
    0,
    1
  ),
  (
    'ten_streak',
    'reverse_brain',
    'classic',
    'challenge',
    '一击即中',
    '连续正确10次',
    'face-orange-up',
    'coin',
    20,
    10,
    'max_combo',
    20,
    0,
    1
  ),
  (
    'perfect_round',
    'reverse_brain',
    'classic',
    'reaction',
    '百发百中',
    '正确率达到100%（单局）',
    'face-purple-wink',
    'gem',
    5,
    1,
    'perfect_round',
    30,
    0,
    1
  ),
  (
    'combo_master',
    'reverse_brain',
    'classic',
    'challenge',
    '连击达人',
    '连续正确50次',
    'face-teal-right',
    'gem',
    10,
    50,
    'max_combo',
    40,
    0,
    1
  ),
  (
    'reverse_master',
    'reverse_brain',
    'classic',
    'growth',
    '反向大师',
    '累计游戏时间达到10小时',
    'face-yellow-cool',
    'coin',
    30,
    10,
    'total_play_hours',
    50,
    0,
    1
  ),
  (
    'cold_brain',
    'reverse_brain',
    'classic',
    'hidden',
    '无情大脑',
    '单局失误0次通关（困难难度）',
    'face-pink-dizzy',
    'gem',
    20,
    1,
    'hard_no_miss_round',
    60,
    1,
    1
  )
ON DUPLICATE KEY UPDATE
  game_key = VALUES(game_key),
  game_mode = VALUES(game_mode),
  category = VALUES(category),
  title = VALUES(title),
  description = VALUES(description),
  icon = VALUES(icon),
  reward_type = VALUES(reward_type),
  reward_amount = VALUES(reward_amount),
  target_value = VALUES(target_value),
  condition_key = VALUES(condition_key),
  sort_order = VALUES(sort_order),
  is_hidden = VALUES(is_hidden),
  is_enabled = VALUES(is_enabled),
  updated_at = CURRENT_TIMESTAMP;
